### ISSUE TITLE
Cresswell et al. Mapping the breast cancer metastatic cascade onto ctDNA using genetic and epigenetic clonal tracking. Nat Communication 2020

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1087]
https://www.nature.com/articles/s41467-020-15047-9

This can be a great study for demonstrating ctdna, genomic evolution and timeline features in patient view.

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)
