### ISSUE TITLE
Kevin Litchfield et al. Meta-analysis of tumor- and T cell-intrinsic mechanisms of sensitization to checkpoint inhibition. Cell. 2021.

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#1366]
https://pubmed.ncbi.nlm.nih.gov/33508232/

- [ ] [create an issue on datahub](https://github.com/cBioPortal/datahub/issues/new) before curating a study (one issue per study) and copy this checklist to the issue tracker
- [ ] List information of the dataset/paper in the issue, e.g. pmid, paper link, suppl file link
- [ ] Document the curation process, e.g. how and by whom the data was transformed
- [ ] Follow [the data checklist](https://github.com/cBioPortal/datahub/issues/248)
- [ ] Create a pull request to datahub once the data is curated
- [ ] Push to triage portal
- [ ] Import into  msk and public portal database
- [ ] Update the default quick select study list see https://github.com/cBioPortal/cbioportal/issues/5831 (only for studies that are not overlapping with existing ones; only for human tumors, not cell lines)
- [ ] Update [cBioPortal news](https://github.com/cBioPortal/cbioportal/blob/master/docs/News.md)

**Comment by yichaoS** [comment]
Study is doing analysis using 12 different cohort - needs to trace back to the 12 publications to find the data; the paper supp itself doesn't provide any. 
Quoting here,
"we collated raw exome/transcriptome data across multiple studies and cancer types, totaling n = 1,008 CPI-treated patients (termed the “CPI1000+ cohort”; Figure 1) from 12 individual cohorts"
![image](https://user-images.githubusercontent.com/5973438/117866743-7a67dc00-b265-11eb-814c-c947d4fe26f6.png)

**Comment by immuneAI** [comment]
Is this dataset available publicly?
