### ISSUE TITLE
Missing meta files in TCGA (Provisional) studies

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#18]
Some meta files are missing, and therefor the data files cannot be loaded.

- [x] meta_clinical_supp_oncotree.txt
- [x] meta_gistic_genes_amp.txt
- [x] meta_gistic_genes_del.txt
- [x] meta_mutsig.txt

**Comment by pieterlukasse** [comment]
@n1zea144 @zheins could you help us with this one?

**Comment by sandertan** [comment]
Fixed in https://github.com/cBioPortal/datahub/pull/31
