### ISSUE TITLE
checklist for a new study

### ISSUE THREAD

**Issue by jjgao** [cBioPortal/datahub#248]
@ritikakundra do we have a checklist for a new study. Could you refine the list below?

- [ ] Does study name and study ID follow our convention? e.g. Tumor_Type (Institue, Journal Year); brca_mskcc_2015. For `mixed` studies, let's not use `mixed` and decide case by case.
- [ ] is study meta data complete? e.g. pmid, group of PUBLIC
- [ ] were all samples profiled with WES/WGS? If not, is gene panel file curated?
- [ ] with matched normal?
- [ ] when pushing data out from msk-impact, germline mutations should be removed (unless they are used in the paper)
- [ ] are oncotree codes of all samples curated; Cancer Type and Cancer Type Detailed needs to be added in addition to Oncotree Code
- [ ] clinical sample and patient data with meta files
- [ ] mutations data with meta files
- [ ] MAF is based on hg19
- [ ] MAF with 2 isoforms: uniprot and mskcc
- [ ] CNA data with meta files
- [ ] CNA segment data with meta files
- [ ] Expression data including z-scores with meta files
- [ ] Case-lists for all profiles.
- [ ] Passes Validation
- [ ] Manual checking (Niki or JJ): MSKCC or Triage Portal

**Comment by jjgao** [comment]
@ritikakundra if data does not exist, you can also check it off. The purpose of a checklist is to check one by one.

To utilize this checklist, one option would be creating a pull request per study with this checklist in the PR.

**Comment by jjgao** [comment]
cc'ing @schultzn to see if he has anything to add.

**Comment by ritikakundra** [comment]
@jjgao ok. Added a few more things

**Comment by jjgao** [comment]
Thanks, @ritikakundra. Let's start to use this checklist when pushing out new studies?

**Comment by ritikakundra** [comment]
@yichaoS @rmadupuri Our checklist for any dataset that goes public.

**Comment by jjgao** [comment]
@ritikakundra @yichaoS @rnugraha let's also try to improve this checklist over time. For new studies, could you create a pull request per study and paste this checklist there? Thanks.

**Comment by schultzn** [comment]
looks good to me!
