### ISSUE TITLE
Missing 5 meta files in thca_tcga study

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/datahub#28]
These files in the `thca_tcga` study are missing meta files:

- [ ] data_CNA.txt
- [ ] data_methylation_hm450.txt
- [ ] data_mutations_extended.txt
- [ ] data_RNA_Seq_v2_expression_median.txt
- [ ] data_rppa_Zscores.txt

**Comment by sandertan** [comment]
Fixed in https://github.com/cBioPortal/datahub/pull/31
